// Global using directives

global using GameSaveFile = CGDFANINCGL;
global using GameGlobals = LFNJDEGJLLJ;
global using GameTextures = LAHFDHJJGKH;
global using GameMenus = BOAPBLKGGHL;
global using GamePlayer = DJEKCMMMFJM;
global using GameDialog = FMHJNNGPMKG;
global using GameAudio = IKPECOJMCAB;
global using GameScreens = JJDCNALMPCI;
global using GameSprites = KPJNFJKBCDF;
global using GameControls = MFCAJFKKFFE;
global using GameKeyboard = BCJPMAHPHEP;
global using GameCollision = LFDENAEGJBJ;
global using HarmonyLib;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using BepInEx;
global using BepInEx.Configuration;
global using BepInEx.Logging;
global using System.IO;
global using UnityEngine;
global using WECCL.Utils;
global using static WECCL.Utils.TextureUtils;
global using static WECCL.Utils.MenuUtils;
global using static WECCL.Content.CustomContent;
global using static WECCL.Utils.FileNameUtils;
global using static WECCL.Utils.ArrayUtils;
global using static WECCL.Utils.DataSharing;