// Global using directives

global using UnmappedSaveData = GLPGLJAJJOP;
global using UnmappedGlobals = NAEEIFNFBBO;
global using UnmappedTextures = PFKAPGFJKHH;
global using UnmappedMenu = AKFIIKOMPLL;
global using UnmappedPlayer = DFOGOCNBECG;
global using UnmappedPromo = NEGAFEHECNL;
global using UnmappedSound = CHLPMKEGJBJ;
global using UnmappedMenus = LIPNHOMGGHF;
global using UnmappedSprites = MCDCDEBALPI;
global using UnmappedControls = HKJOAJOKOIJ;
global using UnmappedKeyboard = MOIHOCAMOOE;
global using UnmappedBlocks = GIMNNPMAKNJ;
global using UnmappedAnims = MBLIOKEDHHB;
global using HarmonyLib;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using BepInEx;
global using BepInEx.Configuration;
global using BepInEx.Logging;
global using System.IO;
global using UnityEngine;
global using WECCL.API;
global using WECCL.Utils;
global using static WECCL.Utils.TextureUtils;
global using static WECCL.Utils.MenuUtils;
global using static WECCL.Content.CustomContent;
global using static WECCL.Utils.FileNameUtils;
global using static WECCL.Utils.ArrayUtils;
global using static WECCL.Utils.DataSharing;