// Global using directives

global using UnmappedSaveData = CGDFANINCGL;
global using UnmappedGlobals = LFNJDEGJLLJ;
global using UnmappedTextures = LAHFDHJJGKH;
global using UnmappedMenu = BOAPBLKGGHL;
global using UnmappedPlayer = DJEKCMMMFJM;
global using UnmappedPromo = FMHJNNGPMKG;
global using UnmappedSound = IKPECOJMCAB;
global using UnmappedMenus = JJDCNALMPCI;
global using UnmappedSprites = KPJNFJKBCDF;
global using UnmappedControls = MFCAJFKKFFE;
global using UnmappedKeyboard = BCJPMAHPHEP;
global using UnmappedBlocks = LFDENAEGJBJ;
global using UnmappedAnims = BCKHHMIMAEN;
global using HarmonyLib;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using BepInEx;
global using BepInEx.Configuration;
global using BepInEx.Logging;
global using System.IO;
global using UnityEngine;
global using WECCL.API;
global using WECCL.Utils;
global using static WECCL.Utils.TextureUtils;
global using static WECCL.Utils.MenuUtils;
global using static WECCL.Content.CustomContent;
global using static WECCL.Utils.FileNameUtils;
global using static WECCL.Utils.ArrayUtils;
global using static WECCL.Utils.DataSharing;