namespace WECCL.Updates;

internal class V159toV160 : VersionDiff
{
    public V159toV160()
    {
        this.MaterialCountsDiff = new List<int>
        {
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            2,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        };
        this.FleshCountsDiff = new List<int>
        {
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        };
        this.ShapeCountsDiff = new List<int>
        {
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        };
        this.BodyFemaleCountDiff = 0;
        this.FaceFemaleCountDiff = 0;
        this.SpecialFootwearCountDiff = 0;
        this.TransparentHairMaterialCountDiff = 0;
        this.TransparentHairHairstyleCountDiff = 1;
        this.KneepadCountDiff = 0;
        this.MusicCountDiff = 0;
    }
}