namespace WECCL.Updates;

internal class V160toV161 : VersionDiff
{
    public V160toV161()
    {
        this.MaterialCountsDiff = new List<int>
        {
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            0,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            5,
            5,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        };
        this.FleshCountsDiff = new List<int>
        {
            0,
            0,
            2,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        };
        this.ShapeCountsDiff = new List<int>
        {
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        };
        this.BodyFemaleCountDiff = 2;
        this.FaceFemaleCountDiff = 0;
        this.SpecialFootwearCountDiff = 0;
        this.TransparentHairMaterialCountDiff = 0;
        this.TransparentHairHairstyleCountDiff = 1;
        this.KneepadCountDiff = 0;
        this.MusicCountDiff = 0;
    }
}